check50:
  checks:
    hello world:
      - run: python3 hello.py
        stdout: Hello, world!
        exit: 0
    hello world:
      - run: clang hello.c
        stdout: Hello, World!
        exit: 0  
