check50: 
  files: &check50_files
    - !exclude "*"
    - !require prompt.c

submit50:
  files: *check50_files
 
check50:
  checks:
    1 Outputs January:
      - run: g++ prompt.c -lcrypt -lcs50 -lm -o prompt
      - run: ./prompt
        stdin: 1
        stdout: January
        exit: 0
    6 Outputs June:
      - run: g++ prompt -lcrypt -lcs50 -lm -o prompt
      - run: ./prompt
        stdin: 6
        stdout: June
        exit: 0
    12 Outputs December:
      - run: g++ prompt.c -lcrypt -lcs50 -lm -o prompt
      - run: ./prompt
        stdin: 12
        stdout: December
        exit: 0
    -1 Outupts Error No such month in my calendar:
      - run: g++ prompt.c -lcrypt -lcs50 -lm -o prompt
      - run: ./prompt
        stdin: -1
        stdout: Error no such month in my calendar
        exit: 0
