check50:
  checks:
    pallindrom:
      -run: clang palli.c  -lcrypt -lcs50 -lm -o palli
      -run: ./palli
       stdin:
         -1111
         -12321
         -45656
         -10010
        stdout:
          -1111 is a palindrome.
          -12321 is a palindrome.
          -45656 is not a palindrome.
          -10010 is not a palindrome.
         exit:0
