check50:
  checks:
    hello world:
      - run: g++ pallindrome.cpp -lcrypt -lcs50 -lm -o pallindrome
      - run: ./pallindrome
        stdin: 1111
        stdout: 1111 is a pallindrome
        exit: 0
